FROM busybox
RUN mkdir -p /tmp/knowledgeBase
COPY currentAiSolution.keras /tmp/knowledgeBase/currentAiSolution.keras
COPY currentOlsSolution.pkl /tmp/knowledgeBase/currentOlsSolution.pkl
COPY README.md /tmp/knowledgeBase/README.md