FROM busybox
RUN mkdir -p /tmp/codeBase
COPY train_ann.py /tmp/codeBase/train_ann.py
COPY train_ols.py /tmp/codeBase/train_ols.py
COPY model_comparison.py /tmp/codeBase/model_comparison.py
COPY README.md /tmp/codeBase/README.md