FROM busybox
RUN mkdir -p /tmp/learningBase/train /tmp/learningBase/validation
COPY training_data.csv /tmp/learningBase/train/training_data.csv
COPY test_data.csv     /tmp/learningBase/validation/test_data.csv
COPY README.md         /tmp/learningBase/README.md
